name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Flutter using subosito/flutter-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.5.4' # Explicitly specify the Flutter version

      # Flutter Clean - Optional (Clears cache and builds fresh artifacts)
      - name: Flutter Clean
        run: flutter clean

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze the Flutter project source
      - name: Analyze project source
        run: flutter analyze

      # Run Flutter tests
      - name: Run tests
        run: flutter test
